server {
    listen 80;
    server_name _;

    # Forward all requests to the "guillotina" service on port 8080
    location / {
        proxy_pass         http://guillotina:8080;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade            $http_upgrade;
        proxy_set_header   Connection         "upgrade";
        proxy_set_header   Host               $host;
        proxy_set_header   X-Real-IP          $remote_addr;
        proxy_set_header   X-Forwarded-For    $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto  $scheme;
	rewrite ^/VirtualHostBase/[^/]+/[^/]+/Plone/\+\+api\+\+/VirtualHostRoot(/.*)$ /db/Plone$1 break;

    }
}
