from guillotina import configure


values = {
    "af": "Afrikaans",
    "ak": "Akan",
    "ig": "Asụsụ Igbo",
    "ay": "Aymara",
    "az": "Azəri Türkçəsi",
    "id": "Bahasa Indonesia",
    "ms": "Bahasa Melayu",
    "ms-bn": "Bahasa Melayu (Brunei)",
    "ms-my": "Bahasa Melayu (Malaysia)",
    "ms-sg": "Bahasa Melayu (Singapura)",
    "ba": "Bashkir",
    "dz": "Bhutani",
    "bh": "Bihari",
    "bi": "Bislama",
    "bs": "Bosanski",
    "my": "Burmese",
    "ca": "Català",
    "ch": "Chamoru",
    "ch-gu": "Chamoru (Guåhan)",
    "ch-mp": "Chamoru (Notte Mariånas)",
    "co": "Corsu",
    "cy": "Cymraeg",
    "da": "Dansk",
    "da-dk": "Dansk (Danmark)",
    "da-gl": "Dansk (Grønland)",
    "de": "Deutsch",
    "de-be": "Deutsch (Belgien)",
    "de-dk": "Deutsch (Danmark)",
    "de-de": "Deutsch (Deutschland)",
    "de-li": "Deutsch (Liechtenstein)",
    "de-lu": "Deutsch (Luxemburg)",
    "de-ch": "Deutsch (Schweiz)",
    "de-at": "Deutsch (Österreich)",
    "nv": "Din\u00e9 bizaad",
    "dv": "Divehi",
    "et": "Eesti",
    "en": "English",
    "en-as": "English (American Samoa)",
    "en-ai": "English (Anguilla)",
    "en-ag": "English (Antigua and Barbuda)",
    "en-au": "English (Australia)",
    "en-bs": "English (Bahamas)",
    "en-bb": "English (Barbados)",
    "en-bz": "English (Belize)",
    "en-bm": "English (Bermuda)",
    "en-bw": "English (Botswana)",
    "en-io": "English (British Indian Ocean Territory)",
    "en-vg": "English (British Virgin Islands)",
    "en-bn": "English (Brunei)",
    "en-cm": "English (Cameroon)",
    "en-ca": "English (Canada)",
    "en-ky": "English (Cayman Islands)",
    "en-ck": "English (Cook Islands)",
    "en-dm": "English (Dominica)",
    "en-er": "English (Eritrea)",
    "en-et": "English (Ethiopia)",
    "en-fk": "English (Falkland Islands)",
    "en-fj": "English (Fiji)",
    "en-gm": "English (Gambia)",
    "en-gh": "English (Ghana)",
    "en-gi": "English (Gibraltar)",
    "en-gd": "English (Grenada)",
    "en-gu": "English (Guam)",
    "en-gy": "English (Guyana)",
    "en-ie": "English (Ireland)",
    "en-il": "English (Israel)",
    "en-jm": "English (Jamaica)",
    "en-ke": "English (Kenya)",
    "en-ki": "English (Kiribati)",
    "en-ls": "English (Lesotho)",
    "en-lr": "English (Liberia)",
    "en-mw": "English (Malawi)",
    "en-mt": "English (Malta)",
    "en-mu": "English (Mauritius)",
    "en-fm": "English (Micronesia)",
    "en-ms": "English (Montserrat)",
    "en-na": "English (Namibia)",
    "en-nr": "English (Nauru)",
    "en-nz": "English (New Zealand)",
    "en-ng": "English (Nigeria)",
    "en-nu": "English (Niue)",
    "en-nf": "English (Norfolk Island)",
    "en-mp": "English (Northern Mariana Islands)",
    "en-pk": "English (Pakistan)",
    "en-pw": "English (Palau)",
    "en-pg": "English (Papua New Guinea)",
    "en-ph": "English (Philippines)",
    "en-pn": "English (Pitcairn)",
    "en-pr": "English (Puerto Rico)",
    "en-rw": "English (Rwanda)",
    "en-sc": "English (Seychelles)",
    "en-sl": "English (Sierra Leone)",
    "en-sg": "English (Singapore)",
    "en-sb": "English (Solomon Islands)",
    "en-so": "English (Somalia)",
    "en-za": "English (South Africa)",
    "en-sh": "English (St. Helena)",
    "en-kn": "English (St. Kitts-Nevis)",
    "en-lc": "English (St. Lucia)",
    "en-vc": "English (St. Vincent and the Grenadi)",
    "en-sz": "English (Swaziland)",
    "en-tk": "English (Tokelau)",
    "en-to": "English (Tonga)",
    "en-tt": "English (Trinidad and Tobago)",
    "en-tc": "English (Turks and Caicos Islands)",
    "en-vi": "English (U.S. Virgin Islands)",
    "en-us": "English (USA)",
    "en-ug": "English (Uganda)",
    "en-gb": "English (United Kingdom)",
    "en-vu": "English (Vanuatu)",
    "en-ws": "English (Western Samoa)",
    "en-zm": "English (Zambia)",
    "en-zw": "English (Zimbabwe)",
    "es": "Español",
    "es-ar": "Español (Argentina)",
    "es-bo": "Español (Bolivia)",
    "es-cl": "Español (Chile)",
    "es-co": "Español (Colombia)",
    "es-cr": "Español (Costa Rica)",
    "es-cu": "Español (Cuba)",
    "es-us": "Español (EE. UU.)",
    "es-ec": "Español (Ecuador)",
    "es-sv": "Español (El Salvador)",
    "es-es": "Español (España)",
    "es-gt": "Español (Guatemala)",
    "es-gq": "Español (Guinea Ecuatorial)",
    "es-hn": "Español (Honduras)",
    "es-mx": "Español (México)",
    "es-ni": "Español (Nicaragua)",
    "es-pa": "Español (Panamá)",
    "es-py": "Español (Paraguay)",
    "es-pe": "Español (Perú)",
    "es-pr": "Español (Puerto Rico)",
    "es-do": "Español (República Dominicana)",
    "es-uy": "Español (Uruguay)",
    "es-ve": "Español (Venezuela)",
    "eo": "Esperanto",
    "eu": "Euskara",
    "ee": "Eʋegbe",
    "fj": "Fiji",
    "fr": "Français",
    "fr-ad": "Français (Andorra)",
    "fr-be": "Français (Belgique)",
    "fr-bf": "Français (Burkina_Faso)",
    "fr-bi": "Français (Burundi)",
    "fr-bj": "Français (Bénin)",
    "fr-cm": "Français (Cameroun)",
    "fr-ca": "Français (Canada)",
    "fr-km": "Français (Comores)",
    "fr-ci": "Français (Cote d'Ivoire)",
    "fr-dj": "Français (Djibouti)",
    "fr-fr": "Français (France)",
    "fr-ga": "Français (Gabon)",
    "fr-gp": "Français (Guadeloupe)",
    "fr-gn": "Français (Guinée)",
    "fr-gf": "Français (Guyane)",
    "fr-it": "Français (Italie)",
    "fr-lb": "Français (Liban)",
    "fr-lu": "Français (Luxembourg)",
    "fr-mg": "Français (Madagascar)",
    "fr-ml": "Français (Mali)",
    "fr-mq": "Français (Martinique)",
    "fr-yt": "Français (Mayotte)",
    "fr-mc": "Français (Monaco)",
    "fr-pf": "Français (Polynésie française)",
    "fr-re": "Français (Reunion)",
    "fr-gb": "Français (Royaume-Uni)",
    "fr-rw": "Français (Rwanda)",
    "fr-cf": "Français (République centrafricaine)",
    "fr-cg": "Français (République du Congo)",
    "fr-cd": "Français (République démocratique du Congo)",
    "fr-sc": "Français (Seychelles)",
    "fr-ch": "Français (Suisse)",
    "fr-td": "Français (Tchad)",
    "fr-tg": "Français (Togo)",
    "fr-vu": "Français (Vanuatu)",
    "fr-wf": "Français (Wallis-et-Futuna)",
    "fr-nc": "Français Nouvelle-Calédonie)",
    "fr-ht": "French (Haïti)",
    "fr-pm": "French (Saint-Pierre-et-Miquelon)",
    "fy": "Frysk",
    "ff": "Fulfulde",
    "fo": "Føroyska",
    "ga": "Gaeilge",
    "gv": "Gaelg",
    "gl": "Galego",
    "kl": "Greenlandic",
    "gn": "Guarani",
    "gd": "Gàidhlig",
    "ki": "Gĩkũyũ",
    "ho": "Hiri Motu",
    "hr": "Hrvatski",
    "hr-ba": "Hrvatski (Bosna i Hercegovina)",
    "hr-hr": "Hrvatski (Hrvatska)",
    "io": "Ido",
    "ia": "Interlingua",
    "ie": "Interlingue",
    "nr": "IsiNdebele",
    "xh": "IsiXhosa",
    "zu": "IsiZulu",
    "it": "Italiano",
    "it-hr": "Italiano (Croazia)",
    "it-it": "Italiano (Italia)",
    "it-sm": "Italiano (San Marino)",
    "it-si": "Italiano (Slovenia)",
    "it-ch": "Italiano (Svizzera)",
    "ik": "Iñupiaq",
    "jv": "Javanese",
    "mh": "Kajin Ṁajeļ",
    "kr": "Kanuri",
    "kw": "Kernewek",
    "kg": "KiKongo",
    "rw": "Kinyarwanda",
    "rn": "Kirundi",
    "sw": "Kiswahili",
    "sw-ke": "Kiswahili (Kenya)",
    "sw-tz": "Kiswahili (Tanzania)",
    "ht": "Kreyòl ayisyen",
    "kj": "Kuanyama",
    "ku": "Kurdí",
    "la": "Latin",
    "lv": "Latviešu",
    "lt": "Lietuvių",
    "li": "Limburgs",
    "ln": "Lingala",
    "ln-cd": "Lingala (Republíki ya Kongó Demokratíki)",
    "ln-cg": "Lingala (Republíki ya Kongó)",
    "lg": "Luganda",
    "lb": "Lëtzebuergesch",
    "hu": "Magyar",
    "hu-hu": "Magyar (Magyarország)",
    "hu-si": "Magyar (Szlovénia)",
    "mg": "Malagasy",
    "mt": "Malti",
    "mi": "Maori",
    "mo": "Moldavian",
    "na": "Nauru",
    "nd": "Ndebele (North)",
    "nl": "Nederlands",
    "nl-an": "Nederlands (Antillen)",
    "nl-aw": "Nederlands (Aruba)",
    "nl-be": "Nederlands (België)",
    "nl-nl": "Nederlands (Nederland)",
    "nl-sr": "Nederlands (Suriname)",
    "no": "Norsk",
    "nb": "Norsk bokmål",
    "se": "Northern Sámi",
    "ii": "Nuosu",
    "nn": "Nynorsk",
    "oc": "Occitan",
    "om": "Oromo",
    "hz": "Otjiherero",
    "vk": "Ovalingo",
    "ng": "Owambo",
    "pl": "Polski",
    "pt": "Português",
    "pt-ao": "Português (Angola)",
    "pt-br": "Português (Brasil)",
    "pt-cv": "Português (Cabo Verde)",
    "pt-gw": "Português (Guiné-Bissau)",
    "pt-mz": "Português (Moçambique)",
    "pt-pt": "Português (Portugal)",
    "pt-st": "Português (São Tomé e Príncipe)",
    "qu": "Quechua",
    "ty": "Reo Tahiti",
    "rm": "Rhaeto-Romance",
    "ro": "Română",
    "sm": "Samoan",
    "sg": "Sangho",
    "sh": "Serbo-Croatian",
    "st": "Sesotho",
    "tn": "Setswana",
    "tn-za": "Setswana (Aforika Borwa)",
    "tn-bw": "Setswana (Botswana)",
    "sn": "Shona",
    "sq": "Shqip",
    "ss": "SiSwati",
    "ss-za": "SiSwati (Ningizimu_Afrika)",
    "ss-sz": "SiSwati (Umbuso weSwatini)",
    "si": "Singhalese",
    "sk": "Slovenčina",
    "sl": "Slovenščina",
    "so": "Somali",
    "sr": "Srpski",
    "sr-ba": "Srpski (Bosna i Hercegovina)",
    "su": "Sudanese",
    "fi": "Suomi",
    "sv": "Svenska",
    "sv-fi": "Svenska (Finland)",
    "sv-se": "Svenska (Sverige)",
    "tl": "Tagalog",
    "vi": "Tiếng Việt",
    "to": "Tonga",
    "lu": "Tshiluba",
    "ve": "Tshivenḓa",
    "tw": "Twi",
    "tr": "Türkçe",
    "tr-bg": "Türkçe (Bulgaristan)",
    "tr-cy": "Türkçe (Kıbrıs Cumhuriyeti)",
    "tr-tr": "Türkçe (Türkiye)",
    "ug": "Uigur",
    "vo": "Volapük",
    "wa": "Walon",
    "wo": "Wolof",
    "ts": "Xitsonga",
    "yo": "Yorùbá",
    "za": "Zhuang",
    "an": "aragonés",
    "ae": "avesta",
    "bm": "bamanankan",
    "br": "brezhoneg",
    "ny": "chiCheŵa",
    "sc": "sardu",
    "is": "Íslenska",
    "cs": "Čeština",
    "cs-cz": "Čeština (česká republika)",
    "el": "Ελληνικά",
    "el-gr": "Ελληνικά (Ελλάδα)",
    "el-cy": "Ελληνικά (Κύπρος)",
    "uz": "Ўзбекча",
    "be": "Беларускі",
    "bg": "Български",
    "ky": "Кыргыз",
    "mk": "Македонски",
    "mn": "Монгол",
    "ru": "Русский",
    "tg": "Тоҷикӣ",
    "uk": "Українська",
    "ab": "бызшәыа",
    "os": "ирон æвзаг",
    "kv": "коми кыв",
    "aa": "магIарул мацI",
    "ce": "нохчийн мотт",
    "tt": "татарча",
    "tk": "түркменче",
    "cv": "чăваш чĕлхи",
    "cu": "ѩзыкъ словѣньскъ",
    "hy": "Հայերեն",
    "he": "עברית",
    "yi": "ײִדיש",
    "ur": "اردو",
    "ur-in": "اردو (بھارت)",
    "ur-pk": "اردو (پاکستان)",
    "ar": "العربية",
    "ar-il": "العربية (إسرائيل)",
    "ar-jo": "العربية (الأردن)",
    "ar-ae": "العربية (الإمارات العربية المتحدة)",
    "ar-bh": "العربية (البحرين)",
    "ar-dz": "العربية (الجزائر)",
    "ar-sa": "العربية (السعودية)",
    "ar-sd": "العربية (السودان)",
    "ar-so": "العربية (الصومال)",
    "ar-iq": "العربية (العراق)",
    "ar-kw": "العربية (الكويت)",
    "ar-ma": "العربية (المغرب)",
    "ar-ye": "العربية (اليمن)",
    "ar-td": "العربية (تشاد)",
    "ar-tn": "العربية (تونس)",
    "ar-ps": "العربية (دولة فلسطين)",
    "ar-om": "العربية (سلطنة عمان)",
    "ar-sy": "العربية (سوريا)",
    "ar-qa": "العربية (قطر)",
    "ar-lb": "العربية (لبنان)",
    "ar-ly": "العربية (ليبيا)",
    "ar-eg": "العربية (مصر)",
    "ar-mr": "العربية (موريتانيا)",
    "sd": "سنڌي",
    "sd-pk": "سنڌي (پاڪستان)",
    "sd-in": "سنڌي (ڀارت)",
    "fa": "فارسی",
    "ha": "هَوُس",
    "ps": "پښتو",
    "ks": "कॉशुर",
    "ne": "नेपाली",
    "pi": "पालि",
    "mr": "मराठी",
    "sa": "संस्कृत",
    "hi": "हिन्दी",
    "as": "অসমিয়া",
    "bn": "বাংলা",
    "bn-bd": "বাংলা (বাংলাদেশ)",
    "bn-in": "বাংলা (ভারত)",
    "bn-sg": "বাংলা (সিঙ্গাপুর)",
    "pa": "ਪੰਜਾਬੀ",
    "gu": "ગુજરાતી",
    "or": "ଓଡ଼ିଆ",
    "ta": "தமிழ்",
    "ta-in": "தமிழ் (இந்தியா)",
    "ta-sg": "தமிழ் (சிங்கப்பூர்)",
    "te": "తెలుగు",
    "kn": "ಕನ್ನಡ",
    "ml": "മലയാളം",
    "th": "ไทย",
    "lo": "ພາສາລາວ",
    "bo": "བོད་ཡིག",
    "ka": "ქართული",
    "ti": "ትግርኛ",
    "am": "አማርኛ",
    "iu": "ᐃᓄᒃᑎᑐᑦ",
    "oj": "ᐊᓂᔑᓇᐯᒧᐎᓐ",
    "cr": "ᒥᓄᑭᐢ",
    "km": "ខ្មែរ",
    "zh": "中文",
    "ja": "日本語",
    "zh-cn": "简体中文(中国)",
    "zh-sg": "简体中文(新加坡)",
    "zh-tw": "繁體中文(台灣)",
    "zh-hk": "繁體中文(香港)",
    "ko": "한국어",
    "ko-kr": "한국어 (대한민국)",
    "ko-kp": "한국어 (조선민주주의인민공화국)",
    "kk": "\ufed7\ufe8e\ufeaf\ufe8d\ufed7\ufeb8\ufe8e"
}


@configure.vocabulary(name="available_languages")
class AvailableLanguagesVocabulary:
    def __init__(self, context):
        self.context = context
        self.values = values

    def __iter__(self):
        return iter(self.values.values())

    def keys(self):
        return self.values.keys()

    def __contains__(self, value):
        return value in self.values

    def __len__(self):
        return len(self.values)

    def getTerm(self, value):
        return self.values.get(value, None)
